#!/bin/bash

cd $VVIEWER

qmake
if [ $? != "0" ]; then
    exit 1
fi
make
if [ $? != "0" ]; then
    exit 1
fi

export VPLUGINS="librenderdefault.dylib;libdraw-vbo-ext.dylib;libnavigatedefault.dylib"

if [ $# -gt 0 ]
  then
  	export VPLUGINS="$VPLUGINS;lib$1.dylib"
  	if [ $2 == "-sl" ]
  	  then
  	    export VPLUGINS="$VPLUGINS;libshaderloader.dylib"
	fi
else
	export VPLUGINS="$VPLUGINS;libshaderloader.dylib"
fi

viewer/bin/viewerd.app/Contents/MacOS/viewerd
